cmake_minimum_required(VERSION 3.20)

project(bugfix-signalfd-write-einval C)

set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS ON)

add_executable(bugfix-signalfd-write-einval src/main.c)
target_compile_options(bugfix-signalfd-write-einval PRIVATE -Wall -Wextra -Werror)

install(TARGETS bugfix-signalfd-write-einval RUNTIME DESTINATION usr/bin/starry-test-suit)
